import type { Quest, Category, Rarity } from "./types"

// Helper to build a quest with derived xp from rarity + difficulty
const rarityBaseXp: Record<Rarity, number> = {
  COMMON: 50,
  RARE: 120,
  EPIC: 220,
  LEGENDARY: 350,
  MYTHIC: 500,
}

function q(
  id: number,
  title: string,
  description: string,
  category: Category,
  rarity: Rarity,
  difficulty: number,
): Quest {
  return {
    id,
    title,
    description,
    category,
    rarity,
    difficulty,
    xp: rarityBaseXp[rarity] + difficulty * 20,
  }
}

export const QUESTS: Quest[] = [
  // FITNESS QUESTS (1–50)
  q(1,   "Walk for 10 minutes",                        "Take a short walk around your neighborhood to get your blood flowing.",                                 "Fitness", "COMMON", 1),
  q(2,   "Walk for 20 minutes",                        "A longer walk to clear your mind and get some exercise.",                                                "Fitness", "COMMON", 2),
  q(3,   "Do 10 pushups",                              "Complete 10 pushups to build upper body strength.",                                                      "Fitness", "COMMON", 2),
  q(4,   "Do 20 squats",                               "Strengthen your legs with 20 squats.",                                                                   "Fitness", "COMMON", 2),
  q(5,   "Stretch for 5 minutes",                      "Do a quick stretching routine to relax your muscles.",                                                   "Fitness", "COMMON", 1),
  q(6,   "Stretch for 10 minutes",                     "A full body stretch session for flexibility and relaxation.",                                            "Fitness", "RARE", 2),
  q(7,   "Climb stairs for 5 minutes",                 "Find some stairs and get your heart pumping.",                                                           "Fitness", "COMMON", 3),
  q(8,   "Drink 1 liter of water",                     "Stay hydrated! Drink at least 1 liter of water today.",                                                  "Fitness", "COMMON", 1),
  q(9,   "Go for a bike ride",                         "Take your bike out for a spin around the block or longer.",                                              "Fitness", "RARE", 3),
  q(10,  "Do a 15-minute workout",                     "Complete a full body workout targeting all major muscle groups.",                                        "Fitness", "EPIC", 4),
  q(11,  "Do 30 jumping jacks",                        "Get your heart rate up with 30 jumping jacks.",                                                          "Fitness", "COMMON", 1),
  q(12,  "Hold a plank for 30 seconds",                "Engage your core and hold a plank position for 30 seconds.",                                            "Fitness", "COMMON", 2),
  q(13,  "Hold a plank for 1 minute",                  "Challenge your core stability with a full minute plank.",                                                "Fitness", "RARE", 3),
  q(14,  "Do 15 lunges each leg",                      "Strengthen your glutes and quads with alternating lunges.",                                              "Fitness", "COMMON", 2),
  q(15,  "Do 10 burpees",                              "One of the best full-body exercises \u2014 10 burpees done is a win.",                                       "Fitness", "RARE", 3),
  q(16,  "Walk for 30 minutes",                        "A brisk half-hour walk to boost mood and burn calories.",                                                "Fitness", "RARE", 2),
  q(17,  "Drink 2 liters of water",                    "Hit your full daily hydration goal \u2014 2 liters of water.",                                               "Fitness", "RARE", 2),
  q(18,  "Do 20 pushups",                              "Level up your pushup game with a set of 20.",                                                           "Fitness", "RARE", 3),
  q(19,  "Do 50 squats",                               "Serious leg day \u2014 push through 50 squats.",                                                              "Fitness", "EPIC", 4),
  q(20,  "Run for 10 minutes",                         "Put on your shoes and run for 10 continuous minutes.",                                                   "Fitness", "RARE", 3),
  q(21,  "Run for 20 minutes",                         "A solid 20-minute run to get your cardio in.",                                                           "Fitness", "EPIC", 4),
  q(22,  "Do 20 sit-ups",                              "Work your core with a set of 20 sit-ups.",                                                              "Fitness", "COMMON", 2),
  q(23,  "Do 30 crunches",                             "Blast your abs with 30 focused crunches.",                                                               "Fitness", "COMMON", 2),
  q(24,  "Do a wall sit for 45 seconds",               "Hold a wall sit position for 45 burning seconds.",                                                       "Fitness", "RARE", 3),
  q(25,  "Do 10 tricep dips",                          "Use a chair or bench to perform 10 tricep dips.",                                                       "Fitness", "COMMON", 2),
  q(26,  "Do 20 mountain climbers",                    "Get your heart rate up with 20 mountain climber reps.",                                                  "Fitness", "COMMON", 2),
  q(27,  "Yoga for 10 minutes",                        "Follow along with a short yoga routine for balance and flexibility.",                                    "Fitness", "RARE", 2),
  q(28,  "Yoga for 20 minutes",                        "A longer yoga flow to de-stress and improve mobility.",                                                  "Fitness", "EPIC", 3),
  q(29,  "Jump rope for 3 minutes",                    "Grab a rope (or pretend!) and jump for 3 minutes straight.",                                             "Fitness", "RARE", 3),
  q(30,  "Go for a swim",                              "Hit the pool for a refreshing swim session.",                                                            "Fitness", "EPIC", 4),
  q(31,  "Walk 5,000 steps",                           "Aim to hit 5,000 steps throughout your day.",                                                           "Fitness", "RARE", 2),
  q(32,  "Walk 10,000 steps",                          "The gold standard \u2014 reach 10,000 steps today.",                                                          "Fitness", "EPIC", 3),
  q(33,  "Do 5 pull-ups",                              "Find a bar and complete 5 clean pull-ups.",                                                             "Fitness", "RARE", 3),
  q(34,  "Foam roll for 5 minutes",                    "Use a foam roller to loosen tight muscles and aid recovery.",                                          "Fitness", "COMMON", 1),
  q(35,  "Do a 5-minute ab circuit",                   "Complete a short ab circuit: crunches, leg raises, and planks.",                                        "Fitness", "RARE", 2),
  q(36,  "Take the stairs instead of the elevator",    "Choose stairs over elevators for your whole day.",                                                       "Fitness", "COMMON", 1),
  q(37,  "Dance for 10 minutes",                       "Put on your favorite music and dance freely for 10 minutes.",                                            "Fitness", "COMMON", 1),
  q(38,  "Do a 30-minute workout",                     "Commit to a full half-hour exercise session.",                                                           "Fitness", "LEGENDARY", 5),
  q(39,  "Stretch before bed",                         "Wind down with a calming stretching routine before sleep.",                                              "Fitness", "COMMON", 1),
  q(40,  "Morning stretch routine",                    "Start your day with a 5-minute morning stretch.",                                                        "Fitness", "COMMON", 1),
  q(41,  "Do 40 jumping jacks",                        "Push beyond your usual and complete 40 jumping jacks.",                                                  "Fitness", "COMMON", 2),
  q(42,  "Try a new exercise",                         "Look up an exercise you have never done and try it today.",                                              "Fitness", "RARE", 2),
  q(43,  "Climb stairs for 10 minutes",                "A longer stair session to really get your cardio pumping.",                                             "Fitness", "RARE", 3),
  q(44,  "Do a 7-minute HIIT session",                 "High-intensity intervals for 7 intense minutes.",                                                        "Fitness", "EPIC", 4),
  q(45,  "Hike for 30 minutes",                        "Find a trail or hill and hike for at least 30 minutes.",                                                 "Fitness", "EPIC", 3),
  q(46,  "Do 25 push-ups",                             "Power through 25 consecutive push-ups.",                                                                 "Fitness", "RARE", 3),
  q(47,  "Skip breakfast junk food",                   "Start the day with a healthy breakfast instead of processed food.",                                      "Fitness", "COMMON", 2),
  q(48,  "Eat a fruit or vegetable",                   "Add at least one fruit or vegetable to a meal today.",                                                    "Fitness", "COMMON", 1),
  q(49,  "Sleep 7+ hours",                             "Prioritize recovery \u2014 get at least 7 hours of sleep tonight.",                                           "Fitness", "RARE", 2),
  q(50,  "Complete a fitness challenge",               "Pick any online fitness challenge and complete one full day of it.",                                    "Fitness", "LEGENDARY", 5),

  // PRODUCTIVITY QUESTS (51–100)
  q(51,  "Clean your desk",                            "Organize and declutter your workspace for better focus.",                                              "Productivity", "COMMON", 2),
  q(52,  "Organize downloads folder",                  "Sort through your downloads and delete unnecessary files.",                                              "Productivity", "COMMON", 2),
  q(53,  "Reply to one important email",               "Clear that email you have been avoiding.",                                                                "Productivity", "COMMON", 2),
  q(54,  "Study for 20 minutes",                       "Focus on learning something new for 20 uninterrupted minutes.",                                          "Productivity", "COMMON", 2),
  q(55,  "Read 10 pages",                              "Pick up a book and read at least 10 pages.",                                                             "Productivity", "COMMON", 2),
  q(56,  "Finish one pending task",                    "Complete that task you have been putting off.",                                                           "Productivity", "RARE", 3),
  q(57,  "Write tomorrow's plan",                      "Plan your next day for maximum productivity.",                                                            "Productivity", "COMMON", 1),
  q(58,  "Close unused browser tabs",                  "Reduce digital clutter by closing tabs you no longer need.",                                             "Productivity", "COMMON", 1),
  q(59,  "Clear desktop clutter",                      "Organize your computer desktop and remove unnecessary icons.",                                            "Productivity", "COMMON", 1),
  q(60,  "Review your goals",                          "Take time to reflect on and update your personal goals.",                                                "Productivity", "RARE", 2),
  q(61,  "Use the Pomodoro technique",                 "Complete one full 25-minute Pomodoro work session.",                                                     "Productivity", "COMMON", 2),
  q(62,  "Do 3 Pomodoro sessions",                     "Power through three focused 25-minute work blocks.",                                                     "Productivity", "RARE", 3),
  q(63,  "Write a to-do list",                         "Write down everything you need to do today.",                                                            "Productivity", "COMMON", 1),
  q(64,  "Tick off 5 to-do items",                     "Make real progress by completing at least 5 tasks from your list.",                                      "Productivity", "RARE", 3),
  q(65,  "Unsubscribe from 5 emails",                  "Clean up your inbox by unsubscribing from 5 newsletters or spam.",                                       "Productivity", "COMMON", 1),
  q(66,  "Clear your inbox to zero",                   "Respond, archive, or delete until your inbox is empty.",                                                 "Productivity", "EPIC", 4),
  q(67,  "Set 3 priorities for the day",               "Identify the three most important things to accomplish today.",                                          "Productivity", "COMMON", 1),
  q(68,  "Block distracting websites",                 "Use an app or extension to block time-wasting sites for 1 hour.",                                        "Productivity", "RARE", 2),
  q(69,  "Organize your calendar",                     "Review and update your calendar for the upcoming week.",                                                 "Productivity", "RARE", 2),
  q(70,  "Read 20 pages",                              "Level up your reading \u2014 get through 20 full pages.",                                                    "Productivity", "RARE", 2),
  q(71,  "Do a weekly review",                         "Spend 15 minutes reviewing what went well this week and what to improve.",                               "Productivity", "EPIC", 3),
  q(72,  "Create a system for one task",               "Design a repeatable process for something you do often.",                                                "Productivity", "RARE", 3),
  q(73,  "Prepare your workspace",                     "Set up your desk before you start work so you can dive right in.",                                       "Productivity", "COMMON", 1),
  q(74,  "Do your most dreaded task first",            "Eat the frog \u2014 tackle your hardest or most avoided task first thing.",                                   "Productivity", "EPIC", 4),
  q(75,  "Spend 1 hour on deep work",                  "Do one hour of fully focused, distraction-free work.",                                                   "Productivity", "EPIC", 4),
  q(76,  "Write for 15 minutes",                       "Journal, blog, or write freely for 15 uninterrupted minutes.",                                          "Productivity", "COMMON", 2),
  q(77,  "Batch similar tasks",                        "Group similar tasks together and complete them in one sitting.",                                         "Productivity", "RARE", 2),
  q(78,  "Declutter one physical space",               "Pick a corner, shelf, or drawer and tidy it up completely.",                                            "Productivity", "COMMON", 2),
  q(79,  "Turn off phone during work",                 "Put your phone on Do Not Disturb for an entire work session.",                                           "Productivity", "RARE", 3),
  q(80,  "Write a summary of something you learned",   "Summarize a key insight or lesson in your own words.",                                                    "Productivity", "RARE", 2),
  q(81,  "Schedule one meeting",                       "Set up a meeting or call you have been putting off.",                                                    "Productivity", "COMMON", 1),
  q(82,  "Delete old files",                           "Find and delete at least 10 old, unused files from your device.",                                       "Productivity", "COMMON", 1),
  q(83,  "Backup your files",                          "Back up important documents and data to the cloud or external drive.",                                  "Productivity", "RARE", 2),
  q(84,  "Update your resume",                         "Refresh your resume with any recent achievements or skills.",                                            "Productivity", "EPIC", 3),
  q(85,  "Read an industry article",                   "Stay sharp by reading one article relevant to your field.",                                              "Productivity", "COMMON", 1),
  q(86,  "Complete a side project task",               "Work on any personal or side project for at least 20 minutes.",                                         "Productivity", "RARE", 3),
  q(87,  "Review last week's tasks",                   "Look back at what you completed and what needs follow-up.",                                              "Productivity", "COMMON", 1),
  q(88,  "Automate one repetitive task",               "Set up a shortcut, macro, or template to save future time.",                                            "Productivity", "EPIC", 4),
  q(89,  "Learn one new tool or app",                  "Explore a productivity tool or app you have never used.",                                                "Productivity", "RARE", 2),
  q(90,  "Work for 2 hours without distraction",       "Two full hours of uninterrupted, focused deep work.",                                                   "Productivity", "LEGENDARY", 5),
  q(91,  "Draft a project outline",                    "Write a structured outline for a project you want to start.",                                            "Productivity", "RARE", 3),
  q(92,  "Organize your notes app",                    "Sort, tag, and clean up your notes or note-taking app.",                                                 "Productivity", "COMMON", 2),
  q(93,  "Set a SMART goal",                           "Write down one Specific, Measurable, Achievable, Relevant, Time-bound goal.",                           "Productivity", "RARE", 2),
  q(94,  "Finish a chapter of a book",                 "Read an entire chapter without stopping.",                                                               "Productivity", "RARE", 2),
  q(95,  "Create a filing system",                     "Organize your documents into a logical folder structure.",                                               "Productivity", "RARE", 2),
  q(96,  "Declutter your phone apps",                  "Delete apps you haven't used in over a month.",                                                         "Productivity", "COMMON", 1),
  q(97,  "Start a project you've delayed",             "Take the very first action on a project that has been sitting on your list.",                            "Productivity", "EPIC", 4),
  q(98,  "Do a brain dump",                            "Write down every thought, worry, or idea on your mind without filtering.",                               "Productivity", "RARE", 2),
  q(99,  "Prepare tomorrow's outfit",                  "Lay out your clothes the night before to save morning decision energy.",                                 "Productivity", "COMMON", 1),
  q(100, "Complete a full productive day",             "Execute your plan from morning to night without major derailments.",                                     "Productivity", "LEGENDARY", 5),

  // SOCIAL QUESTS (101–150)
  q(101, "Call a family member",                       "Reach out to a family member you have not spoken to recently.",                                          "Social", "COMMON", 2),
  q(102, "Text a friend",                              "Send a message to a friend just to say hi.",                                                             "Social", "COMMON", 1),
  q(103, "Thank someone",                              "Express gratitude to someone who helped you.",                                                           "Social", "COMMON", 1),
  q(104, "Compliment someone",                         "Give a genuine compliment to someone today.",                                                            "Social", "COMMON", 1),
  q(105, "Start a conversation",                       "Initiate a conversation with someone new or a colleague.",                                               "Social", "RARE", 3),
  q(106, "Check in on someone",                        "Ask someone how they are doing and really listen.",                                                      "Social", "COMMON", 2),
  q(107, "Reconnect with an old friend",               "Message someone you have not talked to in a while.",                                                     "Social", "RARE", 2),
  q(108, "Send a positive message",                    "Share an encouraging message with someone who might need it.",                                           "Social", "COMMON", 1),
  q(109, "Ask someone how they are doing",             "Check in genuinely and listen to their response.",                                                       "Social", "COMMON", 1),
  q(110, "Have a phone-free conversation",             "Put away your phone during a conversation.",                                                             "Social", "RARE", 2),
  q(111, "Write a heartfelt letter",                   "Write a handwritten or typed letter to someone you care about.",                                         "Social", "EPIC", 3),
  q(112, "Have lunch with someone",                    "Share a meal with a friend, colleague, or family member.",                                               "Social", "RARE", 2),
  q(113, "Give someone a gift",                        "Surprise someone with a thoughtful, small gift.",                                                        "Social", "RARE", 3),
  q(114, "Help someone with a task",                   "Offer your time to assist someone with something they need.",                                            "Social", "RARE", 2),
  q(115, "Plan a get-together",                        "Organize a meetup, even something small and casual.",                                                    "Social", "EPIC", 3),
  q(116, "Make someone laugh",                         "Tell a joke, share a meme, or do something that genuinely makes someone laugh.",                         "Social", "COMMON", 1),
  q(117, "Introduce yourself to someone new",          "Walk up to someone you do not know and introduce yourself.",                                             "Social", "RARE", 3),
  q(118, "Attend a social event",                      "Go to a party, meetup, or community event.",                                                             "Social", "EPIC", 4),
  q(119, "Join an online community",                   "Find and join a forum, Discord, or group related to your interests.",                                    "Social", "RARE", 2),
  q(120, "Comment on someone's post",                  "Leave a genuine, thoughtful comment on a friend's social media post.",                                   "Social", "COMMON", 1),
  q(121, "Share something that inspired you",          "Send a video, article, or quote to a friend you think will appreciate it.",                              "Social", "COMMON", 1),
  q(122, "Have a deep conversation",                   "Go beyond small talk and have a meaningful discussion with someone.",                                    "Social", "EPIC", 3),
  q(123, "Resolve a conflict",                         "Reach out to someone there is tension with and work toward resolution.",                                 "Social", "LEGENDARY", 5),
  q(124, "Celebrate someone's win",                    "Acknowledge and genuinely celebrate a friend or colleague's achievement.",                              "Social", "COMMON", 1),
  q(125, "Listen without interrupting",                "In your next conversation, focus entirely on listening without cutting in.",                              "Social", "RARE", 3),
  q(126, "Volunteer for something",                    "Offer your time or skills to help a community cause or event.",                                          "Social", "EPIC", 3),
  q(127, "Say yes to an invitation",                   "Accept an invite you would normally decline and show up.",                                               "Social", "RARE", 3),
  q(128, "Ask someone for advice",                     "Reach out to someone you respect and ask for their perspective.",                                        "Social", "COMMON", 2),
  q(129, "Mentor or teach someone",                    "Share your knowledge or experience with someone who could benefit.",                                     "Social", "EPIC", 3),
  q(130, "Write a positive review",                    "Leave a glowing review for a local business, app, or creator you love.",                                 "Social", "COMMON", 1),
  q(131, "Apologize sincerely",                        "Offer a genuine apology to someone you may have wronged.",                                               "Social", "RARE", 3),
  q(132, "Hold the door for someone",                  "A small act of courtesy that makes someone's day a little better.",                                     "Social", "COMMON", 1),
  q(133, "Donate to a cause",                          "Contribute \u2014 even a small amount \u2014 to a cause that matters to you.",                                "Social", "EPIC", 2),
  q(134, "Smile at a stranger",                        "Flash a genuine smile at someone you pass on the street.",                                               "Social", "COMMON", 1),
  q(135, "Cook for someone",                           "Prepare a home-cooked meal to share with someone you care about.",                                       "Social", "EPIC", 3),
  q(136, "Video call a faraway friend",                "Schedule and complete a video call with someone who lives far away.",                                    "Social", "RARE", 2),
  q(137, "Recommend something you love",               "Suggest a book, show, or podcast to a friend with genuine enthusiasm.",                                  "Social", "COMMON", 1),
  q(138, "Spend quality time with family",             "Dedicate at least 30 minutes of intentional time with family members.",                                 "Social", "RARE", 2),
  q(139, "Join a group activity",                      "Participate in a group sport, class, or hobby session.",                                                 "Social", "EPIC", 3),
  q(140, "Offer to help someone",                      "Proactively ask someone if they need help with anything.",                                               "Social", "COMMON", 1),
  q(141, "Write 3 things you appreciate about a friend", "Think about a friend and note three qualities you genuinely love.",                                    "Social", "COMMON", 1),
  q(142, "Play a game with someone",                   "Get together for a board game, card game, or video game session.",                                       "Social", "RARE", 2),
  q(143, "Put your phone away at dinner",              "Keep your phone off the table and be fully present during a meal.",                                      "Social", "RARE", 2),
  q(144, "Tell someone you love them",                 "Express your affection directly and sincerely to someone close to you.",                                 "Social", "COMMON", 1),
  q(145, "Attend a virtual event",                     "Join an online talk, webinar, or social event and actively participate.",                                "Social", "RARE", 2),
  q(146, "Check in on someone you're worried about",   "Reach out specifically to someone you feel may be struggling.",                                         "Social", "EPIC", 3),
  q(147, "Ask a thoughtful question",                  "In a conversation, ask a question that shows you were genuinely listening.",                             "Social", "COMMON", 1),
  q(148, "Collaborate on something",                   "Work with someone else on a creative or practical project.",                                             "Social", "RARE", 3),
  q(149, "Build a new friendship",                     "Make genuine effort to develop a friendship with an acquaintance.",                                      "Social", "LEGENDARY", 4),
  q(150, "Throw or attend a get-together",             "Host or attend a gathering that brings people you care about together.",                                 "Social", "LEGENDARY", 5),

  // MINDFULNESS QUESTS (151–200)
  q(151, "Meditate for 5 minutes",                     "Sit quietly and focus on your breath for 5 minutes.",                                                   "Mindfulness", "COMMON", 2),
  q(152, "Meditate for 10 minutes",                    "A longer meditation session for deeper relaxation.",                                                      "Mindfulness", "RARE", 3),
  q(153, "Sit quietly for 10 minutes",                 "Do nothing \u2014 just sit and be present.",                                                                 "Mindfulness", "RARE", 3),
  q(154, "Watch the sunset",                           "Take time to watch and appreciate the sunset.",                                                         "Mindfulness", "RARE", 1),
  q(155, "Watch the sunrise",                          "Wake up early and witness the sunrise.",                                                                "Mindfulness", "EPIC", 3),
  q(156, "Practice gratitude",                         "Write down three things you are grateful for.",                                                         "Mindfulness", "COMMON", 1),
  q(157, "Journal for 10 minutes",                     "Write down your thoughts and feelings.",                                                                "Mindfulness", "RARE", 2),
  q(158, "Deep breathing exercise",                    "Practice deep breathing for 5 minutes.",                                                                "Mindfulness", "COMMON", 1),
  q(159, "Spend 15 minutes offline",                   "Disconnect from all screens and be present.",                                                           "Mindfulness", "RARE", 2),
  q(160, "Reflect on your day",                        "Think about what went well and what you learned.",                                                      "Mindfulness", "COMMON", 1),
  q(161, "Body scan meditation",                       "Slowly bring attention to each part of your body from head to toe.",                                    "Mindfulness", "RARE", 2),
  q(162, "Meditate for 20 minutes",                    "A deep, extended meditation for serious calm and focus.",                                               "Mindfulness", "EPIC", 4),
  q(163, "Write 5 gratitude statements",               "Go deeper than usual \u2014 write 5 specific things you are grateful for.",                                 "Mindfulness", "RARE", 2),
  q(164, "Take a mindful shower",                      "Be fully present during your shower \u2014 notice every sensation.",                                         "Mindfulness", "COMMON", 1),
  q(165, "Practice box breathing",                     "Inhale 4 counts, hold 4, exhale 4, hold 4 \u2014 repeat 5 times.",                                          "Mindfulness", "COMMON", 1),
  q(166, "Mindful eating",                             "Eat one meal slowly, without distractions, savoring every bite.",                                       "Mindfulness", "RARE", 2),
  q(167, "Observe nature for 10 minutes",              "Sit outside and simply watch the trees, sky, or animals around you.",                                   "Mindfulness", "COMMON", 1),
  q(168, "Write down your worries",                    "Put your worries on paper to get them out of your head.",                                               "Mindfulness", "COMMON", 2),
  q(169, "Visualize your ideal day",                   "Spend 5 minutes vividly imagining how your perfect day would look.",                                   "Mindfulness", "RARE", 2),
  q(170, "Forgive someone (or yourself)",              "Consciously let go of resentment toward yourself or another person.",                                   "Mindfulness", "LEGENDARY", 4),
  q(171, "Do a guided meditation",                     "Follow along with a guided meditation app or video.",                                                    "Mindfulness", "RARE", 2),
  q(172, "Count your blessings",                       "Spend a few quiet minutes counting what is going right in your life.",                                  "Mindfulness", "COMMON", 1),
  q(173, "Walk in silence",                            "Go for a walk without headphones and stay fully aware of your surroundings.",                           "Mindfulness", "RARE", 2),
  q(174, "Avoid complaining for one day",              "Catch yourself before every complaint and choose not to voice it.",                                     "Mindfulness", "EPIC", 4),
  q(175, "Sit with an emotion",                        "Notice what you are feeling right now and sit with it without judgment.",                               "Mindfulness", "RARE", 3),
  q(176, "Take 10 deep breaths",                       "Stop what you are doing and take 10 slow, intentional deep breaths.",                                   "Mindfulness", "COMMON", 1),
  q(177, "Practice a loving-kindness meditation",      "Send mental goodwill to yourself and others through this classic technique.",                           "Mindfulness", "EPIC", 3),
  q(178, "Journal about your values",                  "Write about what matters most to you and why.",                                                         "Mindfulness", "RARE", 2),
  q(179, "Spend time in silence",                      "Sit in complete silence for at least 10 minutes with no input whatsoever.",                             "Mindfulness", "RARE", 3),
  q(180, "Reflect on a past mistake",                  "Examine a past mistake with compassion and identify what you learned.",                                 "Mindfulness", "RARE", 3),
  q(181, "Create a morning ritual",                    "Design and execute a calm, intentional morning routine.",                                                "Mindfulness", "EPIC", 3),
  q(182, "Listen to calming music",                    "Put on relaxing music and do nothing else for 10 minutes.",                                             "Mindfulness", "COMMON", 1),
  q(183, "Practice mindful walking",                   "Walk slowly and pay attention to each step, breath, and sensation.",                                     "Mindfulness", "RARE", 2),
  q(184, "Spend time in nature",                       "Go outside and immerse yourself in a natural setting for at least 20 minutes.",                         "Mindfulness", "RARE", 2),
  q(185, "Write a letter to your future self",         "Reflect on where you are now and write to the person you hope to become.",                             "Mindfulness", "EPIC", 3),
  q(186, "Observe your thoughts without reacting",     "Watch your thoughts arise and pass without engaging with them.",                                       "Mindfulness", "EPIC", 4),
  q(187, "Set an intention for the day",               "Before anything else, decide on one intention that guides your day.",                                    "Mindfulness", "COMMON", 1),
  q(188, "Appreciate a small moment",                  "Notice and genuinely appreciate one small, ordinary moment today.",                                     "Mindfulness", "COMMON", 1),
  q(189, "Do a digital detox afternoon",               "Stay off all devices for an entire afternoon.",                                                         "Mindfulness", "LEGENDARY", 5),
  q(190, "Identify one negative thought pattern",      "Notice a recurring unhelpful thought and write about it without judgment.",                             "Mindfulness", "RARE", 3),
  q(191, "Listen to a mindfulness podcast",            "Tune in to an episode focused on mental wellness or mindfulness.",                                      "Mindfulness", "COMMON", 1),
  q(192, "Practice acceptance",                        "Identify one thing out of your control and consciously choose to accept it.",                           "Mindfulness", "RARE", 3),
  q(193, "Unplug before bed",                          "Put away all screens at least 30 minutes before sleeping.",                                             "Mindfulness", "RARE", 2),
  q(194, "Doodle or color mindlessly",                 "Grab paper and draw or color with no goal \u2014 just let your hand move.",                                  "Mindfulness", "COMMON", 1),
  q(195, "Create a calming playlist",                  "Curate a playlist of songs that make you feel calm and peaceful.",                                      "Mindfulness", "COMMON", 1),
  q(196, "Spend 1 hour in nature",                     "Dedicate a full hour to being outside, away from screens and noise.",                                   "Mindfulness", "EPIC", 3),
  q(197, "Practice non-judgment for a day",            "Notice when you judge people or situations and consciously let it go.",                                 "Mindfulness", "LEGENDARY", 5),
  q(198, "Pause before reacting",                      "In any tense moment today, pause for 5 seconds before responding.",                                     "Mindfulness", "RARE", 3),
  q(199, "Write about what brings you joy",            "List and reflect on the people, places, and things that genuinely make you happy.",                     "Mindfulness", "COMMON", 1),
  q(200, "Complete a full day with intention",         "Live your entire day with deliberate awareness from morning to night.",                                  "Mindfulness", "LEGENDARY", 5),

  // ADVENTURE QUESTS (201–250)
  q(201, "Explore a new street",                       "Walk down a street you have never been to before.",                                                     "Adventure", "COMMON", 2),
  q(202, "Visit a new coffee shop",                    "Try a coffee shop you have never been to.",                                                             "Adventure", "RARE", 2),
  q(203, "Take a different route home",                "Change up your usual commute for a new experience.",                                                    "Adventure", "COMMON", 1),
  q(204, "Spend time in a park",                       "Visit a local park and enjoy nature.",                                                                  "Adventure", "COMMON", 1),
  q(205, "Walk without headphones",                    "Go for a walk and listen to the sounds around you.",                                                    "Adventure", "RARE", 2),
  q(206, "Visit a new place",                          "Go somewhere you have never been before.",                                                              "Adventure", "EPIC", 4),
  q(207, "Photograph something interesting",           "Take a photo of something that catches your eye.",                                                      "Adventure", "COMMON", 1),
  q(208, "Watch people in a public space",             "Sit and observe life happening around you.",                                                            "Adventure", "RARE", 2),
  q(209, "Explore your neighborhood",                  "Take a walk and discover new spots nearby.",                                                            "Adventure", "COMMON", 2),
  q(210, "Try a new activity",                         "Do something you have never done before.",                                                              "Adventure", "LEGENDARY", 4),
  q(211, "Try a new restaurant",                       "Have a meal at a restaurant you have never visited.",                                                   "Adventure", "RARE", 2),
  q(212, "Try a new cuisine",                          "Cook or order food from a cuisine you have never eaten.",                                               "Adventure", "RARE", 2),
  q(213, "Visit a museum or gallery",                  "Spend time exploring art, history, or science at a local museum.",                                      "Adventure", "EPIC", 3),
  q(214, "Go to a farmer's market",                   "Browse a local farmer's market and pick up something new.",                                            "Adventure", "RARE", 2),
  q(215, "Attend a local event",                       "Find and go to a festival, market, or community event in your area.",                                   "Adventure", "EPIC", 3),
  q(216, "Watch a foreign film",                       "Watch a movie from a country or culture different from your own.",                                       "Adventure", "RARE", 1),
  q(217, "Read a map and navigate manually",           "Get somewhere using a paper or printed map instead of GPS.",                                            "Adventure", "RARE", 3),
  q(218, "Go on a day trip",                           "Travel somewhere at least an hour away for the day.",                                                   "Adventure", "EPIC", 4),
  q(219, "Visit a bookstore",                          "Browse a bookstore and buy or note something that catches your eye.",                                   "Adventure", "COMMON", 1),
  q(220, "Sit at a caf\u00e9 without your phone",         "Spend at least 20 minutes at a caf\u00e9 observing the world around you.",                                   "Adventure", "RARE", 2),
  q(221, "Watch the stars",                            "Go outside at night and spend time looking at the night sky.",                                          "Adventure", "RARE", 2),
  q(222, "Go to a concert or live performance",        "Attend any kind of live music, comedy, or theatrical show.",                                             "Adventure", "EPIC", 3),
  q(223, "Hike a new trail",                           "Find a trail you have not hiked before and complete it.",                                               "Adventure", "EPIC", 4),
  q(224, "Try a water activity",                       "Go kayaking, paddleboarding, swimming, or any water-based activity.",                                   "Adventure", "EPIC", 4),
  q(225, "Explore a new part of your city",            "Visit a district, neighborhood, or area you have rarely or never been to.",                            "Adventure", "RARE", 2),
  q(226, "Wake up and go somewhere spontaneously",     "Without planning, get up and head somewhere interesting.",                                             "Adventure", "EPIC", 3),
  q(227, "Stargaze for 20 minutes",                    "Lie outside and stargaze with intention \u2014 try to find constellations.",                                 "Adventure", "RARE", 2),
  q(228, "Try a new sport",                            "Pick up a sport you have never played and give it a real attempt.",                                     "Adventure", "EPIC", 4),
  q(229, "Take a scenic photo walk",                   "Spend 30 minutes walking and intentionally photographing beautiful scenes.",                            "Adventure", "RARE", 2),
  q(230, "Do something that scares you mildly",        "Pick something slightly outside your comfort zone and do it.",                                         "Adventure", "EPIC", 4),
  q(231, "Buy something from a local shop",            "Support a small, local business by making a purchase there today.",                                     "Adventure", "COMMON", 1),
  q(232, "Visit a historic landmark",                  "Go to a historic site near you and learn something about its history.",                                 "Adventure", "RARE", 2),
  q(233, "Spend a day as a tourist in your own city",  "Pretend you're a visitor and explore your city with fresh eyes.",                                       "Adventure", "EPIC", 3),
  q(234, "Find a hidden gem nearby",                   "Discover a lesser-known spot, trail, or venue in your area.",                                           "Adventure", "RARE", 3),
  q(235, "Ride public transit for fun",                "Hop on a bus or train with no specific destination and see where you end up.",                          "Adventure", "RARE", 2),
  q(236, "Go to an open mic night",                    "Attend an open mic, stand-up, or poetry night at a local venue.",                                       "Adventure", "RARE", 3),
  q(237, "Try an extreme or bold activity",            "Do something physically bold: a zip line, ropes course, or escape room.",                               "Adventure", "LEGENDARY", 5),
  q(238, "Cook a recipe from a new country",           "Find and cook a dish from a country you've never tried food from.",                                   "Adventure", "RARE", 3),
  q(239, "Read outside",                               "Take your book or e-reader to a park, bench, or garden and read there.",                                "Adventure", "COMMON", 1),
  q(240, "Visit a flea market or thrift shop",         "Browse secondhand treasures at a local flea market or thrift store.",                                  "Adventure", "RARE", 2),
  q(241, "Watch a sunrise from a new location",        "Find a special vantage point to watch the sunrise you've never been to.",                             "Adventure", "EPIC", 3),
  q(242, "Attend a workshop or class",                 "Sign up for and attend a skill-building workshop or class.",                                            "Adventure", "EPIC", 3),
  q(243, "Go for a solo outing",                       "Take yourself somewhere fun \u2014 a movie, lunch, or gallery \u2014 completely alone.",                      "Adventure", "RARE", 2),
  q(244, "Draw a map of your neighborhood",            "From memory or observation, sketch out your local area.",                                               "Adventure", "RARE", 2),
  q(245, "Visit a library",                            "Explore your local library and pick up a book or just browse.",                                         "Adventure", "COMMON", 1),
  q(246, "Plan a future trip",                         "Research and plan a trip somewhere you have always wanted to go.",                                       "Adventure", "RARE", 2),
  q(247, "Have a picnic",                              "Pack some food and have a proper picnic somewhere outside.",                                             "Adventure", "RARE", 2),
  q(248, "Spend a day without planning",               "Let the day unfold without an agenda \u2014 say yes to whatever comes.",                                     "Adventure", "EPIC", 3),
  q(249, "Catch a live sporting event",                "Go see a local sports game or match in person.",                                                         "Adventure", "EPIC", 3),
  q(250, "Take a trip to a completely new city",       "Travel to a city you have never visited and explore it.",                                                "Adventure", "LEGENDARY", 5),

  // DOPAMINE DETOX QUESTS (251–300)
  q(251, "No phone for 30 minutes",                    "Put your phone away for just 30 minutes.",                                                              "Dopamine Detox", "COMMON", 2),
  q(252, "No social media for 1 hour",                 "Stay off all social media platforms for an hour.",                                                      "Dopamine Detox", "RARE", 3),
  q(253, "Eat without screens",                        "Have a meal without watching or scrolling anything.",                                                   "Dopamine Detox", "COMMON", 2),
  q(254, "Disable notifications for an hour",          "Turn off all notifications and enjoy the silence.",                                                     "Dopamine Detox", "RARE", 2),
  q(255, "Leave phone in another room",                "Keep your phone out of sight for a while.",                                                             "Dopamine Detox", "RARE", 2),
  q(256, "No YouTube for 2 hours",                     "Resist the urge to watch videos for 2 hours.",                                                         "Dopamine Detox", "EPIC", 3),
  q(257, "No TikTok for 2 hours",                      "Stay away from TikTok for 2 hours.",                                                                   "Dopamine Detox", "EPIC", 3),
  q(258, "No Instagram for 2 hours",                   "Keep the app closed for 2 full hours.",                                                                 "Dopamine Detox", "EPIC", 3),
  q(259, "Read instead of scrolling",                  "Replace scrolling time with reading a book.",                                                           "Dopamine Detox", "RARE", 2),
  q(260, "Spend one hour screen-free",                 "No screens at all for one full hour.",                                                                  "Dopamine Detox", "LEGENDARY", 4),
  q(261, "No streaming for one evening",               "Skip your usual shows tonight and do something else instead.",                                           "Dopamine Detox", "EPIC", 3),
  q(262, "No phone for 1 hour",                        "Level up the challenge \u2014 one full hour with the phone completely off.",                             "Dopamine Detox", "RARE", 3),
  q(263, "No social media for a full day",             "Stay completely off all social media from morning to night.",                                           "Dopamine Detox", "LEGENDARY", 5),
  q(264, "Delete one addictive app",                   "Remove the app you waste the most time on from your phone.",                                            "Dopamine Detox", "EPIC", 3),
  q(265, "Check your screen time stats",               "Open your screen time report and honestly reflect on what you see.",                                    "Dopamine Detox", "COMMON", 1),
  q(266, "Set screen time limits",                     "Configure daily app limits for your most-used apps.",                                                   "Dopamine Detox", "RARE", 2),
  q(267, "Wake up without checking your phone",        "Get through your entire morning routine before looking at your phone.",                                 "Dopamine Detox", "RARE", 3),
  q(268, "No phone during meals today",                "Put the phone away for every meal you eat today.",                                                      "Dopamine Detox", "RARE", 3),
  q(269, "Replace phone with a book before bed",       "Swap your bedtime scrolling for reading a real book.",                                                  "Dopamine Detox", "RARE", 2),
  q(270, "Charge your phone in a different room at night", "Keep your phone out of your bedroom while you sleep.",                                             "Dopamine Detox", "RARE", 2),
  q(271, "Use grayscale mode for a day",               "Switch your phone to grayscale and notice how it changes your usage.",                                  "Dopamine Detox", "RARE", 2),
  q(272, "No news for one day",                        "Avoid news apps, websites, and TV for a full 24 hours.",                                               "Dopamine Detox", "EPIC", 3),
  q(273, "Do a boring task without entertainment",     "Wash dishes, fold laundry, or clean without any audio or video.",                                       "Dopamine Detox", "COMMON", 2),
  q(274, "Spend an afternoon offline",                 "Stay off all devices from noon until evening.",                                                         "Dopamine Detox", "EPIC", 4),
  q(275, "Track your phone pickups for a day",         "Count how many times you pick up your phone in a single day.",                                         "Dopamine Detox", "COMMON", 1),
  q(276, "Go for a walk without music or podcasts",    "Leave the audio at home and just walk in real-world sound.",                                             "Dopamine Detox", "RARE", 2),
  q(277, "No games for a full day",                    "Skip mobile or video games for the entire day.",                                                        "Dopamine Detox", "EPIC", 3),
  q(278, "Replace scrolling with journaling",          "Every time you feel the urge to scroll, write in a journal instead.",                                    "Dopamine Detox", "EPIC", 3),
  q(279, "Have a screen-free morning",                 "Keep all screens off until lunchtime.",                                                                 "Dopamine Detox", "EPIC", 4),
  q(280, "Do a full day digital detox",                "Avoid all digital devices for an entire day.",                                                          "Dopamine Detox", "LEGENDARY", 5),
  q(281, "Unfollow 10 accounts",                       "Curate your feed by unfollowing 10 accounts that don't add value.",                                    "Dopamine Detox", "COMMON", 1),
  q(282, "No phone for 2 hours",                       "Two full hours without even glancing at your phone.",                                                   "Dopamine Detox", "EPIC", 4),
  q(283, "Notice urges without acting on them",        "When you feel the urge to check your phone, just notice it and wait 5 minutes.",                        "Dopamine Detox", "RARE", 3),
  q(284, "No fast content for one day",                "Avoid Reels, Shorts, and TikTok \u2014 only consume long-form content or none.",                            "Dopamine Detox", "EPIC", 3),
  q(285, "Listen to music without multitasking",       "Put on an album and simply listen \u2014 no scrolling, no work.",                                            "Dopamine Detox", "COMMON", 1),
  q(286, "Use a paper notebook instead of phone",      "For one day, write notes by hand instead of on your phone.",                                           "Dopamine Detox", "RARE", 2),
  q(287, "Turn off WiFi for 2 hours",                  "Disconnect your internet completely for two uninterrupted hours.",                                      "Dopamine Detox", "EPIC", 3),
  q(288, "Remove social media apps from your home screen", "Move them to a folder or the last page so they're not instant.",                                  "Dopamine Detox", "RARE", 2),
  q(289, "Watch a full movie without your phone",      "Put the phone in another room and watch a film uninterrupted.",                                        "Dopamine Detox", "RARE", 2),
  q(290, "Boredom challenge: do nothing for 10 minutes", "Sit with boredom \u2014 no phone, no entertainment, nothing.",                                           "Dopamine Detox", "RARE", 3),
  q(291, "Clear all push notifications",               "Turn off every non-essential push notification on your phone.",                                         "Dopamine Detox", "COMMON", 1),
  q(292, "Cook a meal without looking at your phone",  "Cook from memory or a written recipe with your phone in another room.",                                "Dopamine Detox", "RARE", 2),
  q(293, "Screen-free Saturday morning",               "Keep all screens off until midday on a weekend morning.",                                              "Dopamine Detox", "EPIC", 4),
  q(294, "Replace one social media session with exercise", "Next time you open an app mindlessly, close it and move instead.",                                 "Dopamine Detox", "RARE", 3),
  q(295, "No Twitter/X for 48 hours",                  "Stay completely off the platform for two full days.",                                                   "Dopamine Detox", "EPIC", 4),
  q(296, "Read a physical book for 30 minutes",        "Pick up a real paper book and read it without any other devices on.",                                  "Dopamine Detox", "RARE", 2),
  q(297, "Log your screen time for one week",          "Track your daily screen time every day for 7 days and review.",                                        "Dopamine Detox", "LEGENDARY", 4),
  q(298, "Have a conversation without once checking your phone", "Go through an entire conversation without touching your phone.",                               "Dopamine Detox", "RARE", 2),
  q(299, "Spend an evening with no screens at all",    "From dinner until bedtime, keep all screens completely off.",                                          "Dopamine Detox", "LEGENDARY", 5),
  q(300, "Take a 7-day social media break",            "Stay off all social media platforms for an entire week.",                                              "Dopamine Detox", "LEGENDARY", 5),

  // LEARNING QUESTS (301–350)
  q(301, "Learn a new word",                           "Expand your vocabulary by learning a new word.",                                                       "Learning", "COMMON", 1),
  q(302, "Watch an educational video",                 "Spend time learning from an informative video.",                                                       "Learning", "COMMON", 1),
  q(303, "Read an article",                            "Read a full article about a topic of interest.",                                                       "Learning", "COMMON", 1),
  q(304, "Solve a coding challenge",                   "Complete a coding puzzle or exercise.",                                                                "Learning", "RARE", 3),
  q(305, "Learn a keyboard shortcut",                  "Master a new keyboard shortcut to work faster.",                                                       "Learning", "COMMON", 1),
  q(306, "Practice a language",                        "Spend time practicing a foreign language.",                                                             "Learning", "RARE", 2),
  q(307, "Review your notes",                          "Go through notes you have taken and refresh your memory.",                                              "Learning", "COMMON", 1),
  q(308, "Learn a new concept",                        "Study and understand something you did not know before.",                                              "Learning", "RARE", 2),
  q(309, "Study for 30 minutes",                       "Dedicate half an hour to focused learning.",                                                           "Learning", "RARE", 2),
  q(310, "Teach someone something",                    "Share knowledge by teaching someone a concept.",                                                       "Learning", "EPIC", 3),
  q(311, "Listen to an educational podcast",           "Tune in to a full podcast episode about something you want to learn.",                                "Learning", "COMMON", 1),
  q(312, "Take an online course lesson",               "Complete one lesson from an online course platform.",                                                  "Learning", "RARE", 2),
  q(313, "Learn 5 words in a new language",            "Pick any language and memorize 5 new vocabulary words.",                                              "Learning", "COMMON", 2),
  q(314, "Write a summary of what you learned today",  "Recap the most important thing you learned in your own words.",                                        "Learning", "COMMON", 1),
  q(315, "Read a Wikipedia rabbit hole",               "Start at any topic on Wikipedia and follow links for 20 minutes.",                                    "Learning", "COMMON", 1),
  q(316, "Study for 1 hour",                           "A full hour of uninterrupted focused study on any subject.",                                          "Learning", "EPIC", 3),
  q(317, "Learn the history of something",             "Pick any topic \u2014 food, a country, a word \u2014 and research its history.",                           "Learning", "COMMON", 1),
  q(318, "Take notes while watching a video",          "Watch an educational video and take structured notes as you go.",                                     "Learning", "RARE", 2),
  q(319, "Complete a quiz or test",                    "Take any quiz \u2014 trivia, subject review, or certification practice.",                                  "Learning", "RARE", 2),
  q(320, "Practice mental math for 10 minutes",        "Do mental math exercises to sharpen your arithmetic skills.",                                          "Learning", "COMMON", 2),
  q(321, "Learn about a historical event",             "Research a significant historical event you know little about.",                                       "Learning", "COMMON", 1),
  q(322, "Read a scientific paper abstract",           "Find and read the abstract of a research paper in any field.",                                         "Learning", "RARE", 2),
  q(323, "Learn to play a new card or board game",     "Learn the rules and mechanics of a game you have never played.",                                       "Learning", "RARE", 2),
  q(324, "Build a simple project from a tutorial",     "Follow a step-by-step tutorial to build or create something.",                                         "Learning", "EPIC", 3),
  q(325, "Learn a recipe from a different culture",    "Study and understand a recipe from a cuisine you've never cooked.",                                  "Learning", "COMMON", 1),
  q(326, "Complete a chapter of a textbook",           "Read and understand one full chapter of any non-fiction or academic text.",                           "Learning", "RARE", 3),
  q(327, "Practice a musical instrument",              "Spend at least 15 minutes practicing an instrument you own.",                                          "Learning", "RARE", 2),
  q(328, "Learn about a person who inspires you",      "Read a biography entry or watch a documentary about someone you admire.",                             "Learning", "COMMON", 1),
  q(329, "Solve a logic puzzle",                       "Work through a logic puzzle, Sudoku, or similar brain teaser.",                                       "Learning", "RARE", 2),
  q(330, "Learn a magic trick",                        "Watch a tutorial and practice a simple magic trick until you can do it.",                             "Learning", "RARE", 2),
  q(331, "Research a career path",                     "Spend 20 minutes researching a career or skill you are curious about.",                               "Learning", "COMMON", 1),
  q(332, "Learn the basics of a new software",         "Open an unfamiliar tool and work through a beginner tutorial.",                                       "Learning", "RARE", 2),
  q(333, "Memorize a poem or quote",                   "Commit something worth remembering to memory.",                                                        "Learning", "RARE", 2),
  q(334, "Learn origami",                              "Follow a tutorial and fold a complete origami figure.",                                                "Learning", "RARE", 2),
  q(335, "Watch a TED talk",                           "Pick and watch a TED or TEDx talk on a topic that fascinates you.",                                   "Learning", "COMMON", 1),
  q(336, "Read a biography chapter",                   "Read one chapter of a biography about someone interesting.",                                           "Learning", "COMMON", 2),
  q(337, "Learn about a religion or philosophy",       "Research the core beliefs of a religion or philosophy you don't know well.",                          "Learning", "RARE", 2),
  q(338, "Practice typing speed",                      "Do a 10-minute typing test and try to beat your score.",                                               "Learning", "COMMON", 1),
  q(339, "Study a map and learn geography",            "Spend 15 minutes studying a map and learn something new about a region.",                             "Learning", "COMMON", 1),
  q(340, "Learn about a scientific topic",             "Research a science concept \u2014 physics, biology, chemistry \u2014 that interests you.",                   "Learning", "RARE", 2),
  q(341, "Create a mind map",                          "Map out a topic or idea visually using a mind map structure.",                                         "Learning", "RARE", 2),
  q(342, "Do a daily language lesson",                 "Complete one full lesson on Duolingo, Babbel, or another language app.",                              "Learning", "COMMON", 1),
  q(343, "Watch a documentary",                        "Watch a full documentary on any educational topic.",                                                   "Learning", "RARE", 1),
  q(344, "Discuss something you learned with someone", "Share a fact or idea you recently learned in a conversation.",                                         "Learning", "COMMON", 1),
  q(345, "Learn about economics or markets",           "Read or watch content explaining a concept in economics or business.",                                 "Learning", "RARE", 2),
  q(346, "Practice memory techniques",                 "Try a spaced repetition or mnemonic technique to memorize something.",                                "Learning", "RARE", 2),
  q(347, "Read a philosophy text",                     "Read a short text from a philosopher and reflect on its meaning.",                                     "Learning", "RARE", 3),
  q(348, "Complete an online certification module",    "Work through a module from any online certificate program.",                                          "Learning", "EPIC", 3),
  q(349, "Write what you want to learn this month",    "Set clear learning goals for the next 30 days.",                                                      "Learning", "RARE", 2),
  q(350, "Complete an online course",                  "Finish an entire online course from start to end.",                                                   "Learning", "LEGENDARY", 5),

  // HOME QUESTS (351–400)
  q(351, "Wash dishes",                                "Clean up the dishes in your sink.",                                                                    "Home", "COMMON", 1),
  q(352, "Make your bed",                              "Start the day right by making your bed.",                                                              "Home", "COMMON", 1),
  q(353, "Vacuum one room",                            "Give one room a thorough vacuuming.",                                                                  "Home", "COMMON", 2),
  q(354, "Organize a drawer",                          "Pick a drawer and organize its contents.",                                                             "Home", "COMMON", 2),
  q(355, "Clean your workspace",                       "Tidy up your desk or work area.",                                                                      "Home", "COMMON", 1),
  q(356, "Take out the trash",                         "Empty the trash bins in your home.",                                                                   "Home", "COMMON", 1),
  q(357, "Fold clothes",                               "Fold and organize freshly laundered clothes.",                                                         "Home", "COMMON", 1),
  q(358, "Clean a mirror",                             "Wipe down and polish a mirror until spotless.",                                                        "Home", "COMMON", 1),
  q(359, "Wipe surfaces",                              "Dust and clean surfaces around your home.",                                                            "Home", "COMMON", 1),
  q(360, "Tidy your room",                             "Clean and organize your entire room.",                                                                 "Home", "RARE", 3),
  q(361, "Mop the floors",                             "Mop at least one room's floor until it shines.",                                                       "Home", "RARE", 2),
  q(362, "Clean the bathroom",                         "Scrub and sanitize the sink, toilet, and shower or tub.",                                              "Home", "RARE", 3),
  q(363, "Clean the kitchen",                          "Wipe counters, clean the stove, and organize the kitchen.",                                            "Home", "RARE", 3),
  q(364, "Do your laundry",                            "Wash, dry, and put away a full load of laundry.",                                                      "Home", "RARE", 2),
  q(365, "Vacuum the entire home",                     "Vacuum every carpeted room in your home.",                                                             "Home", "EPIC", 3),
  q(366, "Organize your wardrobe",                     "Sort your clothes by type or color and remove anything you no longer wear.",                           "Home", "EPIC", 3),
  q(367, "Declutter one room completely",              "Remove everything that doesn't belong and find it a proper place.",                                  "Home", "EPIC", 4),
  q(368, "Clean out the fridge",                       "Throw away expired food, wipe shelves, and reorganize your fridge.",                                   "Home", "RARE", 2),
  q(369, "Clean windows",                              "Wash the inside of your windows until they are streak-free.",                                         "Home", "RARE", 2),
  q(370, "Fix something that's been broken",           "Repair or address something in your home that you've been ignoring.",                                "Home", "EPIC", 3),
  q(371, "Donate or discard 10 items",                 "Find 10 things to donate or throw away.",                                                             "Home", "RARE", 2),
  q(372, "Wipe down all light switches and doorknobs", "Clean the most-touched spots in your home.",                                                          "Home", "COMMON", 1),
  q(373, "Clean your oven or microwave",               "Scrub the inside of your oven or microwave.",                                                         "Home", "RARE", 2),
  q(374, "Reorganize a kitchen cupboard",              "Take everything out of one cupboard, clean it, and put things back neatly.",                          "Home", "COMMON", 2),
  q(375, "Change your bed sheets",                     "Strip the bed and put on fresh, clean sheets.",                                                        "Home", "COMMON", 1),
  q(376, "Take out recycling",                         "Gather and properly dispose of recyclables.",                                                          "Home", "COMMON", 1),
  q(377, "Deep clean one room",                        "Pick one room and deep clean it from top to bottom.",                                                  "Home", "EPIC", 4),
  q(378, "Clean the bathroom tiles",                   "Scrub the grout and tiles in the bathroom.",                                                          "Home", "RARE", 3),
  q(379, "Organize your pantry",                       "Sort and arrange your pantry items so everything has a clear place.",                                 "Home", "RARE", 2),
  q(380, "Clean under the furniture",                  "Move and clean underneath sofas, beds, and shelves.",                                                  "Home", "RARE", 3),
  q(381, "Decorate or personalize a space",            "Add something that makes a corner or room feel more like you.",                                       "Home", "RARE", 2),
  q(382, "Water your plants",                          "Give your houseplants the water and care they need.",                                                  "Home", "COMMON", 1),
  q(383, "Clean your stovetop",                        "Remove grease and grime from your stovetop or cooker.",                                               "Home", "COMMON", 2),
  q(384, "Wipe down your appliances",                  "Clean the exterior of your major kitchen appliances.",                                                 "Home", "COMMON", 1),
  q(385, "Organize your medicine cabinet",             "Check expiry dates, discard old items, and arrange neatly.",                                          "Home", "COMMON", 1),
  q(386, "Create a cleaning schedule",                 "Write out a weekly cleaning plan and assign tasks to specific days.",                                  "Home", "RARE", 2),
  q(387, "Clean the entryway",                         "Tidy the front door area \u2014 shoes, coats, and floor all sorted.",                                     "Home", "COMMON", 1),
  q(388, "Sweep or clean outdoor space",               "Clean your balcony, porch, or outdoor area.",                                                         "Home", "COMMON", 1),
  q(389, "Install or fix something small",             "Hang a picture, tighten a loose screw, or replace a bulb.",                                          "Home", "RARE", 2),
  q(390, "Cook a proper home-cooked meal",             "Make a full, balanced meal from scratch using fresh ingredients.",                                    "Home", "RARE", 2),
  q(391, "Prepare meals for the week",                 "Batch cook several meals or portions to set yourself up for the week.",                               "Home", "EPIC", 3),
  q(392, "Disinfect high-touch surfaces",              "Sanitize phones, keyboards, remotes, and handles.",                                                    "Home", "COMMON", 1),
  q(393, "Label and organize storage",                 "Label boxes, shelves, or drawers for a more organized home.",                                         "Home", "RARE", 2),
  q(394, "Clean your car interior",                    "Tidy and wipe down the inside of your car.",                                                          "Home", "RARE", 2),
  q(395, "Set up a cozy reading corner",               "Create a comfortable spot in your home dedicated to reading.",                                        "Home", "RARE", 2),
  q(396, "Organize your bookshelf",                    "Arrange your books by genre, author, or color \u2014 and remove any you'll donate.",                       "Home", "COMMON", 2),
  q(397, "Clean your keyboard and mouse",              "Wipe down and disinfect your computer peripherals.",                                                   "Home", "COMMON", 1),
  q(398, "Set up a morning routine area",              "Organize your bedside table or bathroom to make mornings effortless.",                                "Home", "RARE", 2),
  q(399, "Do a full home deep clean",                  "Clean every room in your home thoroughly in a single session.",                                        "Home", "LEGENDARY", 5),
  q(400, "Redesign or rearrange a room",               "Move the furniture and rethink the layout of any room for a fresh feel.",                             "Home", "LEGENDARY", 4),

  // CREATIVITY QUESTS (401–450)
  q(401, "Draw for 10 minutes",                        "Spend 10 minutes drawing anything that comes to mind.",                                               "Creativity", "COMMON", 2),
  q(402, "Write a short story",                        "Write a creative short story or scene.",                                                               "Creativity", "RARE", 3),
  q(403, "Brainstorm 10 ideas",                        "Come up with 10 ideas for anything.",                                                                  "Creativity", "RARE", 2),
  q(404, "Take a creative photo",                      "Capture an artistic or unique photo.",                                                                  "Creativity", "COMMON", 1),
  q(405, "Design something",                           "Create a design for a logo, poster, or anything.",                                                     "Creativity", "RARE", 3),
  q(406, "Sketch an object",                           "Pick an object near you and sketch it.",                                                                "Creativity", "COMMON", 2),
  q(407, "Create a mood board",                        "Compile images and ideas into a mood board.",                                                          "Creativity", "EPIC", 3),
  q(408, "Write in a journal",                         "Express your thoughts through journaling.",                                                             "Creativity", "COMMON", 1),
  q(409, "Invent a product idea",                      "Come up with an idea for a new product.",                                                               "Creativity", "RARE", 2),
  q(410, "Create a logo concept",                      "Design a logo concept for any brand or idea.",                                                          "Creativity", "EPIC", 3),
  q(411, "Write a poem",                               "Express yourself in verse \u2014 any style, any theme.",                                                    "Creativity", "RARE", 2),
  q(412, "Paint or color something",                   "Use watercolor, acrylics, colored pencils, or any medium to create art.",                              "Creativity", "RARE", 2),
  q(413, "Make a collage",                             "Cut and arrange images, text, or textures into a collage.",                                            "Creativity", "RARE", 2),
  q(414, "Record yourself singing or playing",         "Capture a voice note, cover, or original performance.",                                                "Creativity", "RARE", 3),
  q(415, "Write song lyrics",                          "Come up with an original verse or chorus for any style of music.",                                     "Creativity", "RARE", 3),
  q(416, "Doodle for 5 minutes",                       "Let your pen roam freely on paper with zero expectations.",                                            "Creativity", "COMMON", 1),
  q(417, "Create a character",                         "Invent a fictional character: give them a name, personality, and backstory.",                          "Creativity", "RARE", 2),
  q(418, "Make a short video",                         "Shoot and edit a short clip of anything \u2014 nature, yourself, or your surroundings.",                   "Creativity", "RARE", 3),
  q(419, "Redesign an existing logo",                  "Take a well-known logo and reimagine it in your own style.",                                           "Creativity", "EPIC", 3),
  q(420, "Make something with your hands",             "Build, sculpt, sew, or craft anything physical.",                                                       "Creativity", "RARE", 3),
  q(421, "Write the opening of a novel",               "Craft the first 200 words of a story you would love to read.",                                        "Creativity", "EPIC", 3),
  q(422, "Photograph 5 interesting textures",          "Walk around and photograph 5 different, visually compelling textures.",                                "Creativity", "COMMON", 1),
  q(423, "Design a room layout",                       "Sketch or plan the ideal layout for any room \u2014 real or imaginary.",                                   "Creativity", "RARE", 2),
  q(424, "Create a playlist for a mood",               "Curate a playlist that perfectly captures a specific emotion or scenario.",                            "Creativity", "COMMON", 1),
  q(425, "Illustrate a quote",                         "Turn a meaningful quote into a piece of hand-lettered or digital art.",                               "Creativity", "RARE", 2),
  q(426, "Origami a complex figure",                   "Follow a tutorial and fold an intricate origami model.",                                               "Creativity", "RARE", 3),
  q(427, "Create a zine or mini-book",                 "Fold a sheet of paper into a zine and fill it with ideas, art, or stories.",                          "Creativity", "EPIC", 3),
  q(428, "Write a haiku",                              "Express an idea or moment in the classic 5-7-5 syllable haiku form.",                                 "Creativity", "COMMON", 1),
  q(429, "Draw a self-portrait",                       "Attempt a self-portrait \u2014 realism, abstract, or cartoony, your choice.",                              "Creativity", "RARE", 3),
  q(430, "Create a vision board",                      "Assemble images and words that represent your goals and dreams.",                                       "Creativity", "EPIC", 3),
  q(431, "Write a scene with dialogue",                "Write a conversation between two characters in any setting.",                                          "Creativity", "RARE", 3),
  q(432, "Improvise on a musical instrument",          "Play freely without a plan for at least 5 minutes.",                                                   "Creativity", "RARE", 3),
  q(433, "Build something from LEGO or materials at hand", "Construct anything using blocks, household materials, or craft supplies.",                          "Creativity", "RARE", 2),
  q(434, "Decorate something plain",                   "Take a blank notebook, mug, or box and make it uniquely yours.",                                       "Creativity", "COMMON", 1),
  q(435, "Create a digital artwork",                   "Design something using any digital art or design tool.",                                                "Creativity", "RARE", 3),
  q(436, "Start a creative challenge",                 "Begin a 7-day drawing, writing, or photo challenge.",                                                   "Creativity", "RARE", 2),
  q(437, "Redesign your social media profile",         "Revamp your bio, photos, and aesthetic on any platform.",                                              "Creativity", "RARE", 2),
  q(438, "Write a letter from a fictional character",  "Inhabit a character and write a letter in their voice.",                                               "Creativity", "RARE", 3),
  q(439, "Cook something creative",                    "Invent a dish or try an unusual recipe combination.",                                                   "Creativity", "RARE", 3),
  q(440, "Photograph the same thing at different times", "Shoot the same subject at different hours of the day.",                                             "Creativity", "RARE", 2),
  q(441, "Hand-letter something",                      "Write a word or phrase using decorative hand-lettering.",                                              "Creativity", "COMMON", 2),
  q(442, "Create a comic strip",                       "Draw a short 3-panel comic with characters and a punchline.",                                         "Creativity", "RARE", 3),
  q(443, "Record a voice memo story",                  "Tell a short story out loud and record it as a voice note.",                                           "Creativity", "RARE", 2),
  q(444, "Scrapbook a memory",                         "Create a scrapbook page using photos, mementos, or drawings of a special time.",                       "Creativity", "EPIC", 3),
  q(445, "Write a world-building document",            "Create a page of lore, history, or rules for a fictional world.",                                      "Creativity", "EPIC", 3),
  q(446, "Make a paper sculpture",                     "Cut, fold, and arrange paper into a three-dimensional form.",                                          "Creativity", "RARE", 2),
  q(447, "Write a letter to the world",                "Write a statement, manifesto, or message about something you believe in.",                             "Creativity", "RARE", 2),
  q(448, "Create a typography poster",                 "Design a poster where the text itself is the main visual element.",                                    "Creativity", "EPIC", 3),
  q(449, "Write and illustrate a mini children's book", "Create a short picture book with a simple story and illustrations.",                                 "Creativity", "EPIC", 4),
  q(450, "Publish or share your creative work",        "Share a piece of your art, writing, or creation with an audience.",                                    "Creativity", "LEGENDARY", 4),

  // FINANCE QUESTS (451–500)
  q(451, "Track today's expenses",                     "Record everything you spend today.",                                                                    "Finance", "COMMON", 1),
  q(452, "Review subscriptions",                       "Check your subscriptions and cancel unused ones.",                                                      "Finance", "RARE", 2),
  q(453, "Save $5",                                    "Put aside $5 into your savings.",                                                                       "Finance", "RARE", 2),
  q(454, "Update budget",                              "Review and update your monthly budget.",                                                                "Finance", "RARE", 2),
  q(455, "Review bank account",                        "Go through your recent transactions.",                                                                  "Finance", "COMMON", 1),
  q(456, "Compare prices",                             "Research and compare prices before a purchase.",                                                        "Finance", "COMMON", 1),
  q(457, "Plan a financial goal",                      "Set a specific financial goal with a timeline.",                                                        "Finance", "RARE", 2),
  q(458, "Watch a finance video",                      "Learn something new about personal finance.",                                                           "Finance", "COMMON", 1),
  q(459, "Read about investing",                       "Spend time learning about investment options.",                                                         "Finance", "RARE", 2),
  q(460, "Calculate monthly expenses",                 "Add up all your monthly expenses and analyze.",                                                         "Finance", "EPIC", 3),
  q(461, "Track spending for one week",                "Log every purchase you make over 7 full days.",                                                        "Finance", "EPIC", 3),
  q(462, "Cook instead of ordering out",               "Choose to cook a meal today rather than ordering delivery or eating out.",                              "Finance", "COMMON", 2),
  q(463, "Find one way to save money",                 "Identify one specific thing you can spend less on this week.",                                         "Finance", "COMMON", 1),
  q(464, "Read a personal finance book chapter",       "Read one chapter from any personal finance book.",                                                       "Finance", "RARE", 2),
  q(465, "Create an emergency fund plan",              "Map out how you will build a 1\u20133 month emergency fund.",                                               "Finance", "RARE", 2),
  q(466, "Automate a savings transfer",                "Set up an automatic transfer to your savings account.",                                                 "Finance", "EPIC", 3),
  q(467, "Negotiate a bill",                           "Call a service provider and negotiate a better rate.",                                                  "Finance", "EPIC", 4),
  q(468, "Find a free alternative to a paid service",  "Identify a free app or tool that can replace something you pay for.",                                  "Finance", "RARE", 2),
  q(469, "Sell something you no longer need",          "List an item for sale online or at a garage sale.",                                                    "Finance", "RARE", 2),
  q(470, "Research a financial product",               "Compare savings accounts, credit cards, or investment funds.",                                         "Finance", "RARE", 2),
  q(471, "Create a net worth snapshot",                "Add up your assets and subtract your liabilities.",                                                    "Finance", "EPIC", 3),
  q(472, "Avoid one impulse purchase",                 "Notice a desire to spend impulsively and consciously choose not to.",                                   "Finance", "COMMON", 2),
  q(473, "Learn what compound interest is",            "Research and truly understand how compound interest works.",                                            "Finance", "COMMON", 1),
  q(474, "Contribute to a retirement account",         "Make any contribution, no matter how small, to a retirement or pension plan.",                         "Finance", "EPIC", 3),
  q(475, "Make a no-spend day",                       "Get through an entire day without spending any money.",                                                 "Finance", "RARE", 3),
  q(476, "Review your investment portfolio",           "Check your current investments and assess their performance.",                                          "Finance", "RARE", 2),
  q(477, "Set up or update your will",                 "Create or revisit your will and key legal financial documents.",                                        "Finance", "LEGENDARY", 4),
  q(478, "Calculate your hourly rate",                 "Work out what your time is worth based on your income.",                                                "Finance", "COMMON", 1),
  q(479, "Research tax deductions",                    "Look into tax breaks or deductions you might be eligible for.",                                         "Finance", "RARE", 2),
  q(480, "Read an investing article",                  "Spend time reading about stocks, index funds, or ETFs.",                                               "Finance", "COMMON", 1),
  q(481, "Pay off a small debt",                       "Clear a small outstanding balance \u2014 start with the smallest.",                                         "Finance", "EPIC", 3),
  q(482, "Use a cashback or rewards card wisely",      "Make a planned purchase using a rewards card to earn points.",                                          "Finance", "COMMON", 1),
  q(483, "Plan your grocery list",                     "Write a detailed grocery list before shopping to avoid overspending.",                                  "Finance", "COMMON", 1),
  q(484, "Research a side income idea",                "Look into a way you could earn additional income outside your main job.",                              "Finance", "RARE", 2),
  q(485, "Open a savings account",                     "Set up a dedicated savings account if you don't already have one.",                                   "Finance", "RARE", 2),
  q(486, "Check your credit score",                    "Look up your current credit score and understand what affects it.",                                     "Finance", "COMMON", 1),
  q(487, "Learn about index fund investing",           "Research and understand how low-cost index fund investing works.",                                      "Finance", "RARE", 2),
  q(488, "Start a monthly no-spend challenge",         "Commit to avoiding non-essential purchases for one full month.",                                        "Finance", "LEGENDARY", 5),
  q(489, "Review and dispute a charge",                "Look at your bank statement and dispute any incorrect or unfair charge.",                               "Finance", "RARE", 2),
  q(490, "Calculate your savings rate",                "Work out what percentage of your income you are currently saving.",                                     "Finance", "RARE", 2),
  q(491, "Listen to a finance podcast",                "Tune in to a money, investing, or entrepreneurship podcast episode.",                                  "Finance", "COMMON", 1),
  q(492, "Set a 90-day savings goal",                  "Define a specific savings target to reach within the next 3 months.",                                  "Finance", "RARE", 2),
  q(493, "Learn what dollar-cost averaging is",        "Understand this investment strategy and how it reduces risk over time.",                               "Finance", "RARE", 2),
  q(494, "Reduce a recurring expense",                 "Identify and successfully lower one monthly recurring cost.",                                           "Finance", "EPIC", 3),
  q(495, "Write your financial vision",                "Describe in detail what your ideal financial life looks like in 5 years.",                             "Finance", "RARE", 2),
  q(496, "Learn about real estate basics",             "Read about how real estate investment and mortgages work.",                                             "Finance", "RARE", 2),
  q(497, "Create a debt payoff plan",                  "List all your debts and map out a structured repayment strategy.",                                      "Finance", "EPIC", 3),
  q(498, "Track net worth monthly",                    "Commit to calculating and recording your net worth once a month.",                                      "Finance", "EPIC", 3),
  q(499, "Build a 6-month budget",                     "Create a detailed, category-by-category budget for the next 6 months.",                                "Finance", "LEGENDARY", 4),
  q(500, "Achieve a financial milestone",              "Reach any meaningful financial goal \u2014 first $1K saved, debt free, or invested.",                        "Finance", "LEGENDARY", 5),
]

export const CATEGORIES: Category[] = [
  "Fitness",
  "Productivity",
  "Social",
  "Mindfulness",
  "Adventure",
  "Dopamine Detox",
  "Learning",
  "Home",
  "Creativity",
  "Finance",
]

export const MODE_TO_CATEGORY: Record<string, Category | null> = {
  ALL: null,
  FITNESS: "Fitness",
  PRODUCTIVITY: "Productivity",
  SOCIAL: "Social",
  MINDFULNESS: "Mindfulness",
  ADVENTURE: "Adventure",
  DETOX: "Dopamine Detox",
  LEARNING: "Learning",
  HOME: "Home",
  CREATIVITY: "Creativity",
  FINANCE: "Finance",
}
